enabled: true
subfooter:
  content: '[Grav](http://getgrav.org) was <i class="fa fa-code"></i> with <i class="fa fa-heart"></i> by [RocketTheme](http://www.rockettheme.com). Theme Tikva by [Ralf Geschke](https://www.geschke.net) .'
  enabled: true
dropdown:
  enabled: true
  enable_mouseover: false
theme:
  stylesheet: default
  adjust_header: 0
navbar:
  fixed_top: true
  invert: false
  background: default
background:
  repeat: repeat
footer:
  columns: '1'
socialmedia:
  buttons:
    enabled: false
    position: '1'
    size: '2'
    type: '2'
slider:
  enabled: false
  position: '1'
  width: '940'
  height: '500'
  preserve_ratio: true
  interval: '5000'
  pause:
    pause: false
  keyboard:
    keyboard: false
  wrap:
    wrap: false
