Vagrant.configure("2") do |config|
  config.vm.box = "centos/6"
  config.vm.box_check_update = false
  config.vm.hostname = "becomeonewiththecodegithubenv"
  config.vm.network "forwarded_port", guest: 80, host: 8081,
    auto_correct: true
  #config.vm.synced_folder "/home/oss/repositories/scripts/shell", "/home/oss/"
  config.vm.network "public_network", :bridge => "wlp2s0", :ip => "192.168.1.101"
  config.vm.provider "virtualbox" do |virt0|
	virt0.memory = "512"
	virt0.name = "becomeonewiththecodegithubenv"
	virt0.gui = false
  end
  config.vm.provision "ansible" do |ansible|
	ansible.verbose = "v"
	ansible.playbook = "setup.yml"
  end

end
