---
- hosts: localhost
  gather_facts: true
  tasks:
  
  - sendgrid: 
      api_key: "SG.0osQ82J2S_G3Rwjkk6UOMw.LkKJBNLk2R_0hiSYVGScz_RiGdqKjirBJJQ6skvh5Zk"
      from_address: "cmills@opensitesolutions.com"
      to_addresses: 
        - "cmills@opensitesolutions.com"
      subject: "Test using ansible"
      body: "If you are reading this, test was successfull"
    delegate_to: localhost
       
    
